# This is a basic workflow to help you get started with Actions

name: Scheduled Action

on:
  schedule:
    - cron: "*/5 * * * *"
      
jobs:
  scheduled:
    name: scheduled
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo!
      run: echo "hi"
